### ISSUE TITLE
Hard wrap support

### ISSUE THREAD

**Issue by udf2457** [bbrks/wrap#11]
Hi

I haven't tested it, but looking at your code it doesn't seem to support hard wraps ? (i.e. _"break at X characters, no matter what"_)

Would you be able to introduce this enhancement ?

e.g. PHP `wordwrap()` has a `bool $cut_long_words = false` parameter:

> cut_long_words
> If the cut_long_words is set to true, the string is always wrapped at or before the specified width. So if you have a word that is larger than the given width, it is broken apart. (See second example). When false the function does not split the word even if the width is smaller than the word width.

**Comment by bbrks** [comment]
There's currently no ability to break within a word that is longer than the given limit, but I agree it's a feature that should probably be added.

When I get a spare hour or so, I'll take a look.
