### ISSUE TITLE
Go mod incompatible

### ISSUE THREAD

**Issue by udf2457** [bbrks/wrap#14]
I'm getting the following during `go mod tidy` under `go1.15.6 darwin/amd64` :

> go: finding module for package github.com/bbrks/wrap
> go: downloading github.com/bbrks/wrap v2.3.0+incompatible
> go: found github.com/bbrks/wrap in github.com/bbrks/wrap v2.3.0+incompatible

I'm guessing this is because you've got `go 1.13` in go.mod.

Any reason you can't bump it ?  (Or might be this https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean)

P.S. Side note, thanks for your swift work on the hard-wrap #13  ;-)

**Comment by udf2457** [comment]
My bad : `"github.com/bbrks/wrap/v2"`

**Comment by bbrks** [comment]
I'd pushed versions of wrap up to and including v2.3.0 without realising I needed to change the module name in the mod file!

As a side-effect, any attempts to fetch v1 show that incompatible warning. I'm not exactly sure how to fix the situation, unless I can push a valid v1 version tag, or something... 🤷
