### ISSUE TITLE
Extra transitive dependencies appearing in my go.mod/go.sum

### ISSUE THREAD

**Issue by shabbyrobe** [bbrks/wrap#9]
Since the advent of Go modules, I'm starting to see a lot of undesired and unrelated transitive dependency relationships creep into my projects. Testify is an extremely common thing for projects to depend on, but it brings a yaml parser along for the ride, which is the sort of thing I'm quite keen to avoid my projects depending on unless it's strictly necessary.

As there are only three assertions in this whole library, would you be open to considering a PR that replaces them with standard `t.Fail` or `t.Fatal` calls? I concede that I'm in quite a stark minority here with my preference to carefully audit and constrain my dependency lists, but I thought I'd check anyway!

**Comment by bbrks** [comment]
Hi @shabbyrobe!

Sorry, I missed your issue when it was created, as I was on vacation.

Your request is entirely reasonable, and I also don't see a need to pull in those dependencies for testing this package.

Feel free to submit a PR to switch to the builtin test methods.

Thanks in advance
